<?php

return [
    'oracle' => [
        'driver'         => 'oracle',
        'tns'            => env('DB_TNS', ''),
        'host'           => env('DB_HOST', ''),
        'port'           => env('DB_PORT', '1521'),
        'database'       => env('DB_DATABASE', ''),
        'username'       => env('DB_USERNAME', ''),
        'password'       => env('DB_PASSWORD', ''),
        'charset'        => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'         => env('DB_PREFIX', ''),
        'prefix_schema'  => env('DB_SCHEMA_PREFIX', ''),
        'server_version' => env('DB_SERVER_VERSION', '11g'),
    ],
    'luadm' => [
        'driver'         => 'oracle',
        'tns'            => env('LUADM_TNS', ''),
        'host'           => env('LUADM_HOST', ''),
        'port'           => env('LUADM_PORT', '1521'),
        'database'       => env('LUADM_DATABASE', ''),
        'username'       => env('LUADM_USERNAME', ''),

        'password'       => env('LUADM_PASSWORD', ''),
        'prefix'         => env('LUADM_PREFIX', ''),
        'prefix_schema'  => env('LUADM_SCHEMA_PREFIX', ''),
        'charset'        => env('ORACLE_CHARSET', 'AL32UTF8'),
        'server_version' => env('ORACLE_SERVER_VERSION', '12c'),
    ],
    'esp' => [
        'driver'         => 'oracle',
        'tns'            => env('ESP_TNS', ''),
        'host'           => env('ESP_HOST', ''),
        'port'           => env('ESP_PORT', '1521'),
        'database'       => env('ESP_DATABASE', ''),
        'username'       => env('ESP_USERNAME', ''),
        'password'       => env('ESP_PASSWORD', ''),
        'prefix'         => env('ESP_PREFIX', ''),
        'prefix_schema'  => env('ESP_SCHEMA_PREFIX', ''),
        'charset'        => env('ORACLE_CHARSET', 'AL32UTF8'),
        'server_version' => env('ORACLE_SERVER_VERSION', '12c'),
    ],

    'ekp' => [
        'driver'         => 'oracle',
        'tns'            => env('EKP_TNS', ''),
        'host'           => env('EKP_HOST', ''),
        'port'           => env('EKP_PORT', '1521'),
        'database'       => env('EKP_DATABASE', ''),
        'username'       => env('EKP_USERNAME', ''),
        'password'       => env('EKP_PASSWORD', ''),
        'prefix'         => env('EKP_PREFIX', ''),
        'prefix_schema'  => env('EKP_SCHEMA_PREFIX', ''),
        'charset'        => env('ORACLE_CHARSET', 'AL32UTF8'),
        'server_version' => env('ORACLE_SERVER_VERSION', '12c'),
    ],

    'file' => [
        'driver'         => 'oracle',
        'tns'            => env('FILE_TNS', ''),
        'host'           => env('FILE_HOST', ''),
        'port'           => env('FILE_PORT', '1521'),
        'database'       => env('FILE_DATABASE', ''),
        'username'       => env('FILE_USERNAME', ''),
        'password'       => env('FILE_PASSWORD', ''),
        'prefix'         => env('FILE_PREFIX', ''),
        'prefix_schema'  => env('FILE_SCHEMA_PREFIX', ''),
        'charset'        => env('ORACLE_CHARSET', 'AL32UTF8'),
        'server_version' => env('ORACLE_SERVER_VERSION', '12c'),
    ],
];
